name: CI build

on:
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["CI release"]
    branches: [ main ]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    # Main build job used to
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code of the project
      - name: Checkout
        uses: actions/checkout@v2

      # Setup the jdk using version 8 of adoptOpenJDK
      - name: Setup java 8 using adoptOpenJDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8

      # Build the project using
      #   - clean : clean up the workspace
      #   - validate : perform different check like the dependency and plugin version update
      #   - compile : compile the source code.
      #   - test : Perform the tests.
      - name: Build
        run: mvn -ntp clean validate compile test

      # Check changelog update
      - name: Check changelog update
        run: |
          SHA1="$(git log -n1 --format=format:"%H")"
          SHA2="$(echo $(git ls-remote $GITHUB_SERVER_URL"/"$GITHUB_REPOSITORY main) | cut -d " " -f1)"
          CHANGELOG_FILE="docs/CHANGELOG.md"
          FILES="$(git diff --name-only "$SHA1" "$SHA2")"
          if [[ "$FILES" == *"$CHANGELOG_FILE"* ]]; then
            exit 0
          else
            exit 1
          fi